In [ ]:
import numpy as np
import torch

In [ ]:
A tensor is a number, vector, matrix or any n-dimensional array.

Problem Statement
We'll create a model that predicts crop yeilds for apples (target variable) by looking at the average temperature, rainfall and humidity (input variables or features) in different regions.

Here's the training data:

Temp	Rain	Humidity	Prediction
73	67	43	56
91	88	64	81
87	134	58	119
102	43	37	22
69	96	70	103
In a linear regression model, each target variable is estimated to be a weighted sum of the input variables, offset by some constant, known as a bias :

yeild_apple  = w11 * temp + w12 * rainfall + w13 * humidity + b1
It means that the yield of apples is a linear or planar function of the temperature, rainfall & humidity.

Our objective: Find a suitable set of weights and biases using the training data, to make accurate predictions.






Training Data
The training data can be represented using 2 matrices (inputs and targets), each with one row per observation and one column for variable.

In [ ]:

# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

# Target (apples)
targets = np.array([[56], 
                    [81], 
                    [119], 
                    [22], 
                    [103]], dtype='float32')

In [ ]:
Before we build a model, we need to convert inputs and targets to PyTorch tensors.



In [ ]:
# Convert inputs and targets to tensors
tensor_inputs = torch.tensor(inputs)
print("tensor inputs:\n",tensor_inputs)

tensor_targets = torch.tensor(targets)
print("\ntensor targets:\n",tensor_targets)

tensor inputs:
 tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

tensor targets:
 tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [ ]:
Linear Regression Model (from scratch)
The weights and biases can also be represented as matrices, initialized with random values. The first row of w and the first element of b are use to predict the first target variable i.e. yield for apples, and similarly the second for oranges.

In [ ]:
# Weights and biases
weights = torch.randn(1, 3, requires_grad=True)
biases = torch.randn(1, requires_grad=True)
weights_transpose = torch.transpose(weights, 0, 1)

print("Weights:\n",weights)
print("\nBiases:\n",biases)
print("\nweights_transpose:\n",weights_transpose)

Weights:
 tensor([[-0.4051, -0.0801,  1.0918]], requires_grad=True)

Biases:
 tensor([0.9562], requires_grad=True)

weights_transpose:
 tensor([[-0.4051],
        [-0.0801],
        [ 1.0918]], grad_fn=<TransposeBackward0>)


In [ ]:


The model is simply a function that performs a matrix multiplication of the input x and the weights w (transposed) and adds the bias b (replicated for each observation).

In [ ]:
# Define the model
def fit(X, W_t, b): 
    return (X @ W_t) + b

In [ ]:
The matrix obtained by passing the input data to the model is a set of predictions for the target variables.

In [ ]:

# Generate predictions
prediction = fit(tensor_inputs, weights_transpose, biases)
print(prediction)

tensor([[12.9608],
        [26.9137],
        [18.2990],
        [-3.4168],
        [41.7369]], grad_fn=<AddBackward0>)


In [ ]:
# Compare with targets
print(tensor_targets)


tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [ ]:
Because we've started with random weights and biases, the model does not perform a good job of predicting the target varaibles.

In [ ]:
Loss Function
We can compare the predictions with the actual targets, using the following method:

Calculate the difference between the two matrices (preds and targets).
Square all elements of the difference matrix to remove negative values.
Calculate the average of the elements in the resulting matrix.
The result is a single number, known as the mean squared error (MSE).

In [ ]:
# MSE loss
# help(torch.numel)
def mse_loss(pred, target):
    temp = pred - target
    return torch.sum(temp * temp) / temp.numel()

In [ ]:
# Compute loss
loss = mse_loss(prediction, tensor_targets)
print("Loss: ", loss)


Loss:  tensor(3863.5125, grad_fn=<DivBackward0>)


In [ ]:
Loss:  tensor(1375.0640, grad_fn=<DivBackward0>)
The resulting number is called the loss, because it indicates how bad the model is at predicting the target variables. Lower the loss, better the model.

Compute Gradients
With PyTorch, we can automatically compute the gradient or derivative of the loss w.r.t. to the weights and biases, because they have requires_grad set to True.

In [ ]:
# Compute gradients
loss.backward()

In [ ]:
The gradients are stored in the `.grad` property of the respective tensors.

In [ ]:
# Gradients for weights
print(weights, end="\n-------------\n")
print(weights.grad)

tensor([[-0.4051, -0.0801,  1.0918]], requires_grad=True)
-------------
tensor([[ -9457.7451, -11244.5312,  -6552.6807]])


In [ ]:
# Gradients for bias
print(biases, end="\n-------------\n")
print(biases.grad)

tensor([0.9562], requires_grad=True)
-------------
tensor([-113.8025])


In [ ]:
A key insight from calculus is that the gradient indicates the rate of change of the loss, or the slope of the loss function w.r.t. the weights and biases.

If a gradient element is postive,
increasing the element's value slightly will increase the loss.
decreasing the element's value slightly will decrease the loss.
If a gradient element is negative,
increasing the element's value slightly will decrease the loss.
decreasing the element's value slightly will increase the loss.

The increase or decrease is proportional to the value of the gradient.


Finally, we'll reset the gradients to zero before moving forward, because PyTorch accumulates gradients.

In [ ]:
# help(biases.grad.zero_)
weights.grad.zero_()
biases.grad.zero_()
print(weights.grad,end="\n-------\n")
print(biases.grad)

tensor([[0., 0., 0.]])
-------
tensor([0.])


In [ ]:
Adjust weights and biases using gradient descent
​We'll reduce the loss and improve our model using the gradient descent algorithm, which has the following steps:​1. Generate predictions 2. Calculate the loss 3. Compute gradients w.r.t the weights and biases 4. Adjust the weights by subtracting a small quantity proportional to the gradient 5. Reset the gradients to zero

In [ ]:
# Generate predictions
prediction = fit(tensor_inputs, weights.t(), biases)
print(prediction)

tensor([[12.9608],
        [26.9137],
        [18.2990],
        [-3.4168],
        [41.7369]], grad_fn=<AddBackward0>)


In [ ]:
# Calculate the loss
loss = mse_loss(prediction, tensor_targets)
print(loss)

tensor(3863.5125, grad_fn=<DivBackward0>)


In [ ]:
# Compute gradients
loss.backward()

In [ ]:

# Adjust weights & reset gradients
with torch.no_grad():
    weights -= weights.grad * 1e-5
    biases -= biases.grad * 1e-5
    weights.grad.zero_()
    biases.grad.zero_()

In [ ]:

print(weights)

tensor([[-0.3106,  0.0323,  1.1573]], requires_grad=True)


In [ ]:
With the new weights and biases, the model should have a lower loss.

In [ ]:

# Calculate loss
prediction = fit(tensor_inputs, weights.t(), biases)
loss = mse_loss(prediction, tensor_targets)
print(loss)

tensor(1737.7361, grad_fn=<DivBackward0>)


In [ ]:
Train for multiple epochs
To reduce the loss further, we repeat the process of adjusting the weights and biases using the gradients multiple times. Each iteration is called an epoch.

In [ ]:
# Train for 100 epochs
for i in range(100):
    prediction = fit(tensor_inputs, weights.t(), biases)
    loss = mse_loss(prediction, tensor_targets)
    loss.backward()
    with torch.no_grad():
        weights -= weights.grad * 1e-5
        biases -= biases.grad * 1e-5
        weights.grad.zero_()
        biases.grad.zero_()

In [ ]:
# Calculate loss
prediction = fit(tensor_inputs, weights.t(), biases)
loss = mse_loss(prediction, tensor_targets)
print(loss)

tensor(48.8205, grad_fn=<DivBackward0>)


In [ ]:
# Print predictions
print(prediction)

tensor([[ 58.1047],
        [ 87.0573],
        [106.1543],
        [ 26.0372],
        [107.6551]], grad_fn=<AddBackward0>)


In [ ]:
# Print targets
print(tensor_targets)

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])
